<?php declare(strict_types=1);

namespace App\Modules\Security\RequestValidator;

class BadUserAgents
{
    public const BAD_USER_AGENTS = [
        'AhrefsBot',
        'MJ12bot',
        'SemrushBot',
        'DotBot',
        'SeznamBot',
        'Baiduspider',
        'YandexBot',
        'SpiderBot',
        'Exabot',
        'GrapeshotCrawler',
        'CCBot',
        'PetalBot',
        'ZoominfoBot',
        'DataForSeoBot',
        'MegaIndex.ru',
        'BLEXBot',
        'LinkpadBot',
        'Sogou web spider',
        'Scrapy',
        'HttpClient',
        'Python-urllib',
        'curl',
        'Wget',
        'Go-http-client',
        'Java/',
        'libwww-perl',
        'PHPCrawl',
        'WebZIP',
        'sqlmap',
        'nikto',
        'Acunetix',
        'Netsparker',
        'dirbuster',
        'wpscan',
        'owasp',
        'nessus',
        'OpenVAS',
        'Qualys',
        'Burp Suite',
        'ZAP',
        'Arachni',
        'Hydra',
        'Metasploit',
        'Nmap',
        'masscan',
        'zgrab',
        'Xenu Link Sleuth',
        'HTTrack',
        'WinHTTP',
        'WinInet',
        'WebDAV',
        'spbot',
        'SiteLockSpider',
        'Mail.RU_Bot',
        'ia_archiver',
        'archive.org_bot',
        'Barkrowler',
        'BaiduSpark',
        'Ezooms',
        'Genieo',
        'heritrix',
        'IstellaBot',
        'Linguee Bot',
        'lmspider',
        'meanpathbot',
        'Mediatoolkitbot',
        'omgili',
        'PageThing',
        'Panscient.com',
        'proximic',
        'Qwantify',
        'rogerbot',
        'SafeDNSBot',
        'Scanbot',
        'Screaming Frog SEO Spider',
        'SISTRIX',
        'Siteimprove.com',
        'SMTBot',
        'SurveyBot',
        'TurnitinBot',
        'Uptimebot',
        'WebCollage',
        'WebStripper',
        'WebSucker',
        'WebCopier',
        'WebAuto',
        'WebReaper',
        'WebShrinker',
        'WebZIP',
        'Wotbox',
        'YisouSpider',
        'ZmEu',
        'ZumBot'
    ];
}
